### ISSUE TITLE
Installation issue on apple M2

### ISSUE THREAD

**Issue by Machadum** [sigven/vcf2tsv#11]
Hi

I was unfortunately unsuccessful with the installation. Could you please help me with this? Here are the outputs:

`conda install -c bioconda vcf2tsvpy`
```
Channels:
 - bioconda
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides cyvcf2 needed by vcf2tsvpy-0.6.0-pyh0517881_0

Could not solve for environment specs
The following package could not be installed
└─ vcf2tsvpy is not installable because it requires
   └─ cyvcf2, which does not exist (perhaps a missing channel).

```

`cyvcf2`
```
Traceback (most recent call last):
  File "/Users/ipmc/miniconda3/bin/cyvcf2", line 5, in <module>
    from cyvcf2.__main__ import cli
  File "/Users/ipmc/miniconda3/lib/python3.12/site-packages/cyvcf2/__init__.py", line 1, in <module>
    from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
ImportError: dlopen(/Users/ipmc/miniconda3/lib/python3.12/site-packages/cyvcf2/cyvcf2.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '_bcf_hdr_format'

```

Many thanks!

**Comment by sigven** [comment]
Hi Marie-Charlotte, 

Thanks for reporting. I am currently on vacation, will have a look into your issue when I am back in late July.

cc @brentp: got any clue as to cyvcf2 availability on Apple M2?

best,
Sigve

**Comment by pdiakumis** [comment]
Hi @Machadum, since you have an M2 you might need to do the following (I have an M1 and it works) (tip is from https://github.com/conda-forge/miniforge/issues/165#issuecomment-860233092):

```
# create a new environment called env1 with intel packages
CONDA_SUBDIR=osx-64 conda create -n env1 -c bioconda vcf2tsvpy

# make sure that conda commands in this environment use intel packages
conda config --env --set subdir osx-64
```

**Comment by Machadum** [comment]
Thanks a lot for the tip @pdiakumis!
